server:
  port: 8081
  error:
    include-message: always
#Configuracion de spring
spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://xlexgosc:bcEH08skPBU33lCsDE0n2LDzvMO93ZzR@ruby.db.elephantsql.com:5432/xlexgosc?socketTimeout=3
    username: xlexgosc
    password: bcEH08skPBU33lCsDE0n2LDzvMO93ZzR
    driverClassName: org.postgresql.Driver